version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: dota2_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  etl:
    build: .
    environment:
      POSTGRES_DB: dota2_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./sql_scripts:/app/sql_scripts
      - ./data_pipeline:/app/data_pipeline
      - ./logs:/app/logs

volumes:
  postgres_data: 